#file: noinspection SpringBootApplicationYaml
server:
  port: 8222

spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://132.220.59.110"  
              - "http://localhost:4200"  
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - "Authorization"
              - "Content-Type"

      routes:
        - id: USER-SERVICE
          uri: http://user-service:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=0
        - id: ITEM-SERVICE
          uri: http://item-service:8082
          predicates:
            - Path=/api/v1/items/**
          filters:
            - StripPrefix=0
        - id: RECLAMATION-SERVICE
          uri: http://reclamation-service:8086
          predicates:
            - Path=/api/v1/reclamations/**
          filters:
            - StripPrefix=0
        - id: MATCHING-SERVICE
          uri: http://matching-service:8084
          predicates:
            - Path=/api/v1/matchings/**
          filters:
            - StripPrefix=0
        - id: PAYMENT-SERVICE
          uri: http://payment-service:8085
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - StripPrefix=0  # Ne rien enlever du chemin, car ton controller l'attend tel quel
        - id: NOTIFICATION-SERVICE
          uri: http://notification-service:8083
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=0  # Ne rien enlever du chemin, car ton controller l'attend tel quel
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
