apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  selector:
    app: angular-app
  type: LoadBalancer
  ports:
    - port: 80         # Port exposé à l’extérieur
      targetPort: 80   # ✅ doit correspondre à containerPort
      protocol: TCP
